apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  selector:
    app: superset
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
