apiVersion: v1
kind: Service
metadata:
  name: superset-service
spec:
  selector:
    app: superset
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8088
    - name: admin
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
