# apiVersion: v1
# kind: Service
# metadata:
#   name: superset-service
# spec:
#   selector:
#     app: superset
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8088
#   type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
apiVersion: v1
kind: Service
metadata:
name: superset
spec:
selector:
name: superset
type: NodePort
ports:
- name: foo # Actually, no port is needed.
port: 8088
targetPort: 8088
---
apiVersion: v1
kind: Pod
metadata:
name: superset
labels:
name: superset
spec:
containers:
- image: amancevice/superset
name: superset
